### ISSUE TITLE
Roxygenize with OpenAPI description and summary fields

### ISSUE THREAD

**Issue by eaurele** [ropenscilabs/apipkgen#17]
The OpenAPI specification describes a `description` and a `summary` fields that could be used to generate an Roxygen documentation: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#path-item-object , both at the function level and the function parameter level

**Comment by sckott** [comment]
thanks for this - agree, makes sense to use those fields to help generate the manual files. will work onit soon

**Comment by sckott** [comment]
@eaurele reinstall and try again, generates docs now for each fxn, try with bcgov eg. havne't tested with any others yet

**Comment by eaurele** [comment]
Thank you so much!
I opened a PR to handle a few additional quirks of my use case (for reference: [https://data.castoredc.com/api/swagger](url))
#18
