### ISSUE TITLE
Related work - OpenAPITools openapi-generator

### ISSUE THREAD

**Issue by eaurele** [ropenscilabs/apipkgen#19]
Are you aware of [https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/r](https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/r)?

**Comment by eaurele** [comment]
And its Swagger predecessor https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/r that can be tried out at https://generator.swagger.io/

**Comment by sckott** [comment]
yes, i am aware of those. the problem is they are Java tools. You are very welcome to use that instead of this. We may be able to learn from the templating they do perhaps though
