### ISSUE TITLE
Options for tokens? 

### ISSUE THREAD

**Issue by seanthimons** [ropenscilabs/apipkgen#20]
It's unclear how or where a user should include an API token. Is it better to fork the repo and edit the helper functions, or is there a way that a token can be passed for every derived function?

**Comment by sckott** [comment]
Thanks for your question. I'll take a look. I hadn't worked on this in years, so re-familiarizing

**Comment by sckott** [comment]
hi @seanthimons I decided I don't have time to work on this, so I'm archiving the repo to make it clear its not getting any further attention. It's just too much work and most importantly I wouldn't be using this package, which means it would wither on the vine. Have you tried https://github.com/bergant/rapiclient ?
