### ISSUE TITLE
feedback?

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/apipkgen#5]
@bhaskarvk let me know what you think

**Comment by bhaskarvk** [comment]
will do.

**Comment by bhaskarvk** [comment]
How do I call an API which takes input as PATH ?
e.g. 
`http://somehost.net/customers/<CUSTOMER-ID>/`

How do I pass CUSTOMER-ID ?

**Comment by sckott** [comment]
Thanks for the feedback @bhaskarvk  

not currently supported, coming...

**Comment by sckott** [comment]
@bhaskarvk okay, try again after reinstalling `devtools::install_github("ropenscilabs/apipkgen")`, see nscilabs/apipkgen/blob/master/inst/examples/template_crossref2.yml#L6-L10 for example, use the key `path` to specify a path, which is used on the base url for the API, like you have above
